- hosts: all
  become: true

  vars:
    ansible_python_interpreter: '/usr/local/bin/python2.7'

  tasks:
    - include_role:
        name: 'JoergFiedler.freebsd-jailed-syslogd'
      vars:
        jail_net_ip: '10.1.0.10'
        jail_name: 'syslogd'
        jail_freebsd_release: '11.2-RELEASE'
