---
- name: Add syslogd flags to rc.conf
  lineinfile:
    backup: '{{ backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/rc.conf'
    state: present
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertbefore: EOF
  loop:
    - { regexp: '^syslogd_enable=', line: 'syslogd_enable="YES"' }
    - { regexp: '^syslogd_flags=', line: 'syslogd_flags="-n -a {{ syslogd_net }}:* -b {{ jail_net_ip }}"' }
  notify:
    - Reload jail s syslogd

- name: Copy syslog.conf
  template:
    backup: '{{ backup_old_files }}'
    src: 'syslog.conf.j2'
    dest: '{{ jail_home.stdout }}/etc/syslog.conf'
  notify:
    - Reload jail s syslogd

- name: Create all.log file
  copy:
    dest: '{{ jail_home.stdout }}/var/log/all.log'
    content: ''
    force: no
