---
# handlers file for jailed_syslogd
- name: Reload jail s syslogd
  command: |
    /usr/local/bin/iocage exec {{ jail_uuid.stdout }} service syslogd reload
  when: not jail_created is changed

- name: Reload jail s sshd
  command: |
    /usr/local/bin/iocage exec {{ jail_uuid.stdout }} service sshd reload
  when: not jail_created is changed
